import type { AITool } from "@/lib/types"

export const aiTools: AITool[] = [
  {
    id: "1",
    name: "v0",
    description:
      "v0 converts natural language descriptions into code and UI. Build landing pages, full-stack apps, and more with simple text prompts.",
    category: "Development",
    useCases: ["Code Generation", "UI Design", "Prototyping"],
    pricing: "Freemium",
    url: "https://v0.dev",
    rating: 4.8,
    reviewCount: 1245,
    isTrending: true,
  },
  {
    id: "2",
    name: "ChatGPT",
    description:
      "ChatGPT is an AI-powered chatbot developed by OpenAI, based on the GPT architecture. It can engage in conversational dialogue and provide responses that can appear surprisingly human.",
    category: "Chatbots",
    useCases: ["Content Generation", "Research", "Customer Support"],
    pricing: "Freemium",
    url: "https://chat.openai.com",
    rating: 4.9,
    reviewCount: 9876,
    isTrending: true,
  },
  {
    id: "3",
    name: "Perplexity",
    description:
      "Perplexity AI is a conversational search engine that provides direct answers to questions by searching the web and citing sources, combining the power of search engines with AI.",
    category: "Research",
    useCases: ["Information Retrieval", "Research", "Learning"],
    pricing: "Freemium",
    url: "https://perplexity.ai",
    rating: 4.7,
    reviewCount: 2345,
    isTrending: true,
  },
  {
    id: "4",
    name: "Midjourney",
    description:
      "Midjourney is an AI image generation tool that creates images from textual descriptions, similar to OpenAI's DALL-E and Stable Diffusion.",
    category: "Design",
    useCases: ["Image Generation", "Art Creation", "Design Inspiration"],
    pricing: "Paid",
    url: "https://midjourney.com",
    rating: 4.8,
    reviewCount: 5432,
  },
  {
    id: "5",
    name: "DeepSeek",
    description:
      "DeepSeek is an advanced AI chatbot that specializes in deep reasoning and complex problem-solving, particularly useful for technical and scientific queries.",
    category: "Chatbots",
    useCases: ["Technical Support", "Scientific Research", "Problem Solving"],
    pricing: "Freemium",
    url: "https://deepseek.ai",
    rating: 4.6,
    reviewCount: 1876,
  },
  {
    id: "6",
    name: "Grok",
    description:
      "Grok is an AI assistant by xAI designed to answer questions with wit, have a rebellious streak, and access real-time information from the web.",
    category: "Chatbots",
    useCases: ["Information Retrieval", "Entertainment", "Research"],
    pricing: "Paid",
    url: "https://grok.x.ai",
    rating: 4.5,
    reviewCount: 1543,
  },
  {
    id: "7",
    name: "Bolt",
    description:
      "Bolt is an AI-powered development tool that helps developers write, understand, and improve code faster with intelligent code completion and suggestions.",
    category: "Development",
    useCases: ["Code Completion", "Code Review", "Debugging"],
    pricing: "Freemium",
    url: "https://bolt.new",
    rating: 4.7,
    reviewCount: 2134,
  },
  {
    id: "8",
    name: "Jasper",
    description:
      "Jasper is an AI content platform that helps teams create high-quality content faster with AI writing assistance, templates, and collaboration tools.",
    category: "Content Creation",
    useCases: ["Blog Writing", "Marketing Copy", "Social Media Content"],
    pricing: "Paid",
    url: "https://jasper.ai",
    rating: 4.6,
    reviewCount: 3245,
  },
  {
    id: "9",
    name: "Stable Diffusion",
    description:
      "Stable Diffusion is an open-source AI art generation model that creates detailed images based on text descriptions, offering high-quality results with local installation options.",
    category: "Design",
    useCases: ["Image Generation", "Art Creation", "Design"],
    pricing: "Free",
    url: "https://stability.ai",
    rating: 4.7,
    reviewCount: 4532,
  },
  {
    id: "10",
    name: "Claude",
    description:
      "Claude is an AI assistant created by Vercel designed to be helpful, harmless, and honest, with strong capabilities in understanding and generating text.",
    category: "Chatbots",
    useCases: ["Content Generation", "Research", "Customer Support"],
    pricing: "Freemium",
    url: "https://claude.ai",
    rating: 4.8,
    reviewCount: 3421,
  },
  {
    id: "11",
    name: "GitHub Copilot",
    description:
      "GitHub Copilot is an AI pair programmer that offers autocomplete-style suggestions as you code, drawing context from comments and code to suggest individual lines and whole functions.",
    category: "Development",
    useCases: ["Code Generation", "Code Completion", "Programming"],
    pricing: "Paid",
    url: "https://github.com/features/copilot",
    rating: 4.9,
    reviewCount: 7654,
  },
  {
    id: "12",
    name: "Runway",
    description:
      "Runway is an applied AI research company that creates next-generation creation tools, with features for video editing, generation, and visual effects powered by AI.",
    category: "Design",
    useCases: ["Video Generation", "Video Editing", "Visual Effects"],
    pricing: "Freemium",
    url: "https://runway.ml",
    rating: 4.7,
    reviewCount: 2876,
  },
  {
    id: "13",
    name: "Notion AI",
    description:
      "Notion AI is an AI writing assistant integrated into the Notion workspace that helps users draft, edit, summarize, and brainstorm content directly in their documents.",
    category: "Productivity",
    useCases: ["Writing Assistance", "Summarization", "Brainstorming"],
    pricing: "Paid",
    url: "https://notion.so/product/ai",
    rating: 4.6,
    reviewCount: 3421,
  },
  {
    id: "14",
    name: "Hugging Face",
    description:
      "Hugging Face is a platform that provides tools for building, training and deploying state-of-the-art machine learning models, with a focus on natural language processing.",
    category: "Development",
    useCases: ["Model Deployment", "NLP", "Machine Learning"],
    pricing: "Freemium",
    url: "https://huggingface.co",
    rating: 4.8,
    reviewCount: 4532,
  },
  {
    id: "15",
    name: "Synthesia",
    description:
      "Synthesia is an AI video generation platform that creates professional videos from text in minutes, with AI avatars that can speak in multiple languages.",
    category: "Content Creation",
    useCases: ["Video Generation", "Training Videos", "Marketing"],
    pricing: "Paid",
    url: "https://synthesia.io",
    rating: 4.5,
    reviewCount: 1987,
  },
  {
    id: "16",
    name: "Otter.ai",
    description:
      "Otter.ai is an AI-powered meeting assistant that records, transcribes, and summarizes meetings in real-time, making it easy to search and share important information.",
    category: "Productivity",
    useCases: ["Transcription", "Meeting Notes", "Summarization"],
    pricing: "Freemium",
    url: "https://otter.ai",
    rating: 4.6,
    reviewCount: 2345,
  },
  {
    id: "17",
    name: "Grammarly",
    description:
      "Grammarly is an AI writing assistant that helps users improve their writing by checking grammar, spelling, punctuation, clarity, engagement, and delivery mistakes.",
    category: "Content Creation",
    useCases: ["Grammar Checking", "Writing Improvement", "Proofreading"],
    pricing: "Freemium",
    url: "https://grammarly.com",
    rating: 4.7,
    reviewCount: 8765,
  },
  {
    id: "18",
    name: "Replicate",
    description:
      "Replicate is a platform that lets you run machine learning models with a cloud API, without having to set up your own infrastructure or manage dependencies.",
    category: "Development",
    useCases: ["Model Deployment", "AI APIs", "Machine Learning"],
    pricing: "Paid",
    url: "https://replicate.com",
    rating: 4.6,
    reviewCount: 1432,
  },
]

